version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-app-frontend
    container_name: frontend
    ports:
      - 4000:8080
    restart: always
