services:
  db:
    image: postgres:12.0-alpine
    container_name: ct-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_DATABASE:-core}
      - POSTGRES_USER=${SQL_USER:-user}
      - POSTGRES_PASSWORD=${SQL_PASSWORD:-password}
    networks:
      - backend_net
    restart: always

  backend:
    build:
      context: ./backend
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-ddandrea/devops-interview-craftech}/backend:latest
    container_name: ct-backend
    hostname: backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-1}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-*}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DATABASE=${DATABASE:-postgres}
      - SQL_ENGINE=${SQL_ENGINE:-django.db.backends.postgresql}
      - SQL_DATABASE=${SQL_DATABASE:-core}
      - SQL_USER=${SQL_USER:-user}
      - SQL_PASSWORD=${SQL_PASSWORD:-password}
      - SQL_HOST=${SQL_HOST:-db}
      - SQL_PORT=${SQL_PORT:-5432}
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - backend_net
      - frontend_net
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_SERVER
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-ddandrea/devops-interview-craftech}/frontend:latest
    container_name: ct-frontend
    hostname: frontend
    expose:
      - 8080
    networks:
      - frontend_net
    restart: always

  nginx-proxy:
    build:
      context: ./reverse-proxy
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-ddandrea/devops-interview-craftech}/proxy:latest
    container_name: nginx-proxy
    hostname: nginx-proxy
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - NGINX_FQDN=${NGINX_FQDN}
      - NGINX_CERT=${NGINX_CERT:-certificado.crt}
      - NGINX_KEY=${NGINX_KEY:-clave_privada.key}
      - NGINX_CERT_CONTENT=${NGINX_CERT_CONTENT}
      - NGINX_KEY_CONTENT=${NGINX_KEY_CONTENT}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - frontend_net
    restart: always

networks:
  frontend_net:
  backend_net:
    internal: true

volumes:
  postgres_data:
