services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    networks:
      - backend_net
    restart: always

  backend:
    build:
      context: ./backend
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-ddandrea/devops-interview-craftech}/backend:latest
    container_name: ct-backend
    hostname: backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - backend_net
      - frontend_net
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_SERVER
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-ddandrea/devops-interview-craftech}/frontend:latest
    container_name: ct-frontend
    hostname: frontend
    expose:
      - 8080
    networks:
      - frontend_net
    restart: always

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    hostname: nginx-proxy
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - NGINX_FQDN=${NGINX_FQDN}
      - NGINX_CERT=${NGINX_CERT:-certificado.crt}
      - NGINX_KEY=${NGINX_KEY:-clave_privada.key}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/templates:/etc/nginx/templates:ro
      - ./reverse-proxy/certs:/etc/nginx/certs:ro
      - ./reverse-proxy/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - frontend_net
    restart: always

networks:
  frontend_net:
  backend_net:
    internal: true

volumes:
  postgres_data:
