name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
          build-args: |
            REACT_APP_API_SERVER=${{ secrets.REACT_APP_API_SERVER }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull and Restart Services
        run: |
          # crear el .env necesario para el proxy si no existe
          if [ ! -f .env ]; then
            echo "NGINX_FQDN=${{ secrets.NGINX_FQDN }}" > .env
            echo "NGINX_CERT=certificado.crt" >> .env
            echo "NGINX_KEY=clave_privada.key" >> .env
          fi
          
          # actualizar imagenes y reiniciar contenedores
          docker compose pull
          docker compose up -d
          
          # limpieza de imagenes antiguas
          docker image prune -f
